
// CSS custom properties for easy theming
export const cssVariables = {
  light: {
    '--color-primary': '#2196f3',
    '--color-primary-light': '#64b5f6',
    '--color-primary-dark': '#1976d2',
    '--color-secondary': '#4caf50',
    '--color-secondary-light': '#81c784',
    '--color-secondary-dark': '#388e3c',
    '--color-background-graph-light': '#F7F9FB',
    '--color-background-paper': '#ffffff',
    '--color-background-default-light': '#ffffff',
    '--color-text-primary': '#1C1C1C',
    '--color-text-secondary': '#757575',
    '--color-text-tertiary': '#999999',
    '--color-text-disabled': '#bdbdbd',
    '--color-border': '#e0e0e0',
    '--color-shadow': '#000000',
    '--color-button-primary': '#d3d3d3',
    '--color-background-hover': '#f5f5f5',
    '--color-background-information-light': '#E3F5FF',
    '--color-background-neutral-light': '#F7F9FB',
    '--color-background-tertiary-light': '#E5ECF6',
  },

  dark: {
    '--color-primary': '#2196f3',
    '--color-primary-light': '#64b5f6',
    '--color-primary-dark': '#1976d2',
    '--color-secondary': '#4caf50',
    '--color-secondary-light': '#81c784',
    '--color-secondary-dark': '#388e3c',
    '--color-background': '#0a0a0a',
    '--color-background-paper': '#1e1e1e',
    '--color-background-default': '#0a0a0a',
    '--color-text-primary': '#ffffff',
    '--color-text-secondary': '#757575',
    '--color-text-tertiary': '#999999',
    '--color-text-disabled': '#bdbdbd',
    '--color-border': '#e0e0e0',
    '--color-shadow': '#000000',
    '--color-button-primary': '#2196f3',
    '--color-background-hover': '#1e1e1e',
  },
};
